server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservations/** 
        - id: Owner
          uri: http://localhost:8082
          predicates:
            - Path=/owners/** 
        - id: Management
          uri: http://localhost:8083
          predicates:
            - Path=/managements/** 
        - id: reservationStatus
          uri: http://localhost:8084
          predicates:
            - Path= /reservationStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: admin03-reservation
          uri: http://admin03-reservation:8080
          predicates:
            - Path=/reservations/** 
        - id: admin03-owner
          uri: http://admin03-owner:8080
          predicates:
            - Path=/owners/** 
        - id: admin03-management
          uri: http://admin03-management:8080
          predicates:
            - Path=/managements/** 
        - id: admin03-reservationstatus
          uri: http://admin03-reservationstatus:8080
          predicates:
            - Path= /reservationStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
